name: Generate JSDoc

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  jsdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json

      - name: Commit and push JSDoc changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b jsdoc/update-${{ github.run_id }}
          git add docs
          git commit -m "Auto-generate JSDoc" || echo "No changes to commit"
          git push origin jsdoc/update-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: jsdoc/update-${{ github.run_id }}
          title: "Auto-generate JSDoc"
          body: "This PR was automatically created by GitHub Actions to update JSDoc output."
          labels: documentation
