name: Generate JSDoc

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  jsdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json

      - name: Commit and Push JSDoc
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout --orphan $BRANCH_NAME
          git reset --hard
          git clean -fdx
          
          if [ -d "docs" ]; then
            cp -r docs/* .
          else
            echo "No docs generated"
            exit 1
          fi

          git add .
          git commit -m "Update JSDoc output"
          git branch -M jsdoc
          git push -f origin jsdoc