name: Generate JSDoc

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  jsdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install dependencies
        run: npm install

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json

      - name: Upload docs as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: jsdoc
          path: docs/