name: Puppeteer Test

on: [push, pull_request]

jobs:
  puppeteer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install
      
      - name: Standard Page Movement Test
        run: npm test ./tests/puppeteer.test.js
      - name: Theme Toggle Test
        run: npm test ./tests/theme-toggle.test.js