name: Unit Tests # name of the test 

on: [push] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install

      - name: Create Deck Dom Unit Test
        run: npm test ./tests/dom-functions-create-deck.test.js
      - name: Create Deck / Filter / Deck Logic Unit Test
        run: npm test ./tests/unit-test-create-deck.test.js
      - name: Delete Deck Unit Test
        run: npm test ./tests/delete-deck.test.js
      - name: Shuffle Unit Test
        run: npm test ./tests/shuffle.test.js
